### ISSUE TITLE
HttpOnly and Secure flags

### ISSUE THREAD

**Issue by bsittler** [patrickkettner/cookie-change-events#33]
What does the change event look like when a previously-visible cookie becomes invisible because it is replaced by an HttpOnly and/or (when the observer is http: rather than https:) Secure cookie with the same effective domain, path and name?

What happens when an attempted cookie operation fails because it would cause the eviction of a Secure-flagged and/or HttpOnly-flagged cookie by a replacement lacking that/those flag(s)? Is an error indicated? Does any change event fire?

What happens when a browser implementing https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00 prevents an attempt to set/modify/delete a cookie with the special __Secure- or __Host- prefix because of mismatched Secure flag (or domain mismatch, or path mismatch)?

What happens when a browser implementing https://tools.ietf.org/html/draft-ietf-httpbis-cookie-alone-01 prevents an attempt to set/modify/delete a Secure-flagged cookie by a non-"https:" website or otherwise prevents a cookie operation to prevent eviction of higher-security cookies from a lower-security origin?

**Comment by patrickkettner** [comment]
> What does the change event look like when a previously-visible cookie becomes invisible because it is replaced by an HttpOnly and/or (when the observer is http: rather than https:)

the key thing I have kept in mind when asking questions like this is "what would someone who relies on the currently available (i.e. polling) behavior experience". In this case, it would trigger a removal, because they would be unaware of the difference between just straight up deleting it and making it https-only/secure. I could imagine creating an additional [ChangeCause](https://patrickkettner.github.io/cookie-change-events/#enumdef-changecause), but would probably want to think about whether or not that would be prudent.

> What happens when ... 

(this answer applied to the rest of your sections) What happens is exactly what happens today. We think about what happens as two steps.

1. whether or not to throw an error, and
2. whether or not a change event gets fired.

1. Since all of our setting logic is really just sugar on top of the existing document.cookie API, we do not throw and error for any of the scenarios you mention. This is because document.cookie="{{any of those scanarios}}" does not throw an error.
2. Since regardless of what was set, nothing is changed internally, there is no change and therefore there is no reason to fire a change event.

**Comment by bsittler** [comment]
That sounds reasonable to me.
